name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz
    - name: Extract ngrok
      run: tar -xvzf ngrok.tgz
    - name: Auth ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Install XFCE and xrdp
      run: |
        sudo apt-get update
        sudo apt-get install -y xfce4 xfce4-goodies xorg dbus-x11 x11-xserver-utils
        sudo apt-get install -y xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Configure xrdp
      run: |
        echo "xfce4-session" > ~/.xsession
        echo "export XDG_CONFIG_DIRS=/etc/xdg/xdg-xfce:/etc/xdg" >> ~/.xsession
        echo "export XDG_DATA_DIRS=/usr/share/xfce4:/usr/share:/usr/local/share" >> ~/.xsession
        sudo usermod -aG xfce runneradmin
        sudo sed -i 's/port=3389/port=3390/g' /etc/xrdp/xrdp.ini
        sudo systemctl restart xrdp

    - name: Set Password for User
      run: |
        echo "runneradmin:P@ssw0rd!" | sudo chpasswd

    - name: Verify XFCE Installation
      run: |
        dpkg -l | grep xfce4
        dpkg -l | grep xrdp

    - name: Create Tunnel
      run: ./ngrok tcp 3390

    - name: Create and Maintain Tunnel
      run: |
        # Inicia o ngrok em background e salva os logs
        ./ngrok tcp 3390 --log=stdout > ngrok.log 2>&1 &
        
        # Aguarda o túnel ser estabelecido
        sleep 10
        
        # Mantém o workflow rodando enquanto exibe logs em tempo real
        echo "Mantendo o workflow ativo. Conecte-se ao túnel via RDP."
        tail -f ngrok.log
