name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xfce4 xfce4-goodies xorg dbus-x11 x11-apps

    - name: Download and Install ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar -xzf ngrok-v3-stable-linux-amd64.tgz
        chmod +x ngrok

    - name: Authenticate ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start XFCE and ngrok in a loop
      run: |
        while true; do
          # Start XFCE
          startxfce4 &
          XFCE_PID=$!

          # Start ngrok tunnel for X11 (port 5900 for VNC)
          ./ngrok tcp 5900

          # Wait for XFCE to exit (if it does)
          wait $XFCE_PID

          # If XFCE exits, restart it
          echo "XFCE exited, restarting..."
        done
