name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz

    - name: Extract ngrok
      run: tar -xvzf ngrok.tgz

    - name: Auth ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Install XFCE and xrdp
      run: |
        sudo apt-get update
        sudo apt-get install -y xfce4 xfce4-goodies xorg dbus-x11 x11-xserver-utils xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Configure xrdp and XFCE
      run: |
        # Configura o XFCE como sessão padrão para o usuário runneradmin
        echo "xfce4-session" | sudo tee /home/runneradmin/.xsession
        sudo chmod +x /home/runneradmin/.xsession
        sudo chown runneradmin:runneradmin /home/runneradmin/.xsession
        
        # Define XDG_CONFIG_DIRS diretamente para o XRDP
        echo "export XDG_CONFIG_DIRS=/etc/xdg:/usr/share" | sudo tee /etc/xrdp/startwm.sh
        sudo sed -i 's|^#.*startxfce4|startxfce4|' /etc/xrdp/startwm.sh
        sudo chmod +x /etc/xrdp/startwm.sh
        
        # Ajusta a porta do XRDP
        sudo sed -i 's/port=3389/port=3390/g' /etc/xrdp/xrdp.ini
        
        # Reinicia o XRDP para aplicar as mudanças
        sudo systemctl restart xrdp

    - name: Set Password for User
      run: |
        echo "runneradmin:P@ssw0rd!" | sudo chpasswd

    - name: Create and Maintain Tunnel
      run: |
        # Mata qualquer processo ngrok existente localmente
        pkill ngrok || true
        
        # Inicia o ngrok em background e salva os logs
        ./ngrok tcp 3390 --log=stdout > ngrok.log 2>&1 &
        
        # Aguarda o túnel ser estabelecido
        sleep 15
        
        # Verifica se o túnel foi criado com sucesso
        if ! curl -s http://localhost:4040/api/tunnels | grep -q "public_url"; then
          echo "Erro: Túnel ngrok não foi criado. Verifique o token ou sessões ativas em https://dashboard.ngrok.com/agents"
          cat ngrok.log
          exit 1
        fi
        
        # Exibe a URL pública do túnel
        echo "Túnel ngrok ativo. URL pública:"
        curl -s http://localhost:4040/api/tunnels | jq -r .tunnels[0].public_url
        
        # Mantém o workflow ativo enquanto exibe logs
        echo "Mantendo o workflow ativo. Conecte-se ao túnel via RDP."
        tail -f ngrok.log
