name: Windows RDP
on: workflow_dispatch  # Requires manual trigger

jobs:
  rdp_setup:
    runs-on: windows-latest
    timeout-minutes: 240  # 4 hour maximum runtime

    steps:
    - name: Download ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath ngrok

    - name: Authenticate ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Configure RDP
      run: |
        # Enable Remote Desktop
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 1
        
        # Set password for runneradmin user
        $securePassword = ConvertTo-SecureString -AsPlainText "$Env:RDP_PASSWORD" -Force
        Set-LocalUser -Name "runneradmin" -Password $securePassword

        # Allow password authentication
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 0
      env:
        RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}

    - name: Start ngrok tunnel
      id: ngrok
      shell: pwsh
      run: |
        # Start ngrok in background
        Start-Process -FilePath ".\ngrok\ngrok.exe" -ArgumentList "tcp 3389 --log=stdout" -NoNewWindow
        
        # Wait for tunnel to establish
        Start-Sleep -Seconds 15
        
        # Get tunnel URL
        $response = Invoke-RestMethod -Uri "http://localhost:4040/api/tunnels" -Method Get
        $tunnelUrl = $response.tunnels[0].public_url
        
        # Output tunnel information
        Write-Host "Ngrok Tunnel Established: $tunnelUrl"
        echo "tunnel_url=$tunnelUrl" >> $env:GITHUB_OUTPUT

    - name: Display connection information
      run: |
        Write-Host "=============================================="
        Write-Host "RDP Connection Details:"
        Write-Host "Address: ${{ steps.ngrok.outputs.tunnel_url }}"
        Write-Host "Username: runneradmin"
        Write-Host "Password: ${{ secrets.RDP_PASSWORD }}"
        Write-Host "=============================================="
        Write-Host "NOTE: This GitHub Actions run must remain active to maintain the connection."
        Write-Host "This is for EDUCATIONAL PURPOSES ONLY and violates GitHub Terms of Service."

    - name: Keep alive
      run: |
        Write-Host "Maintaining RDP tunnel active for 4 hours..."
        Start-Sleep -Seconds 14400  # 4 hours
